### ISSUE TITLE
Add more metadata to the manager contract

### ISSUE THREAD

**Issue by theref** [electora-vote/electora-app#22]
Should store the endtime of a vote in the contract. This allows two things:
- #18 
- the ability for independent parties to recreate the CBD conditions for decryption.

**Comment by theref** [comment]
Could also add "protocol version". The way ZKP's and Votes are packaged & encrypted must be public and immutable for a specific election. Why?:
- For skeptical users to easily interact with elections whilst using none of electoras tools.
- For independant entities to Validate election results LONG after they have taken place.

**Comment by meatballs** [comment]
it also helps with #16

**Comment by meatballs** [comment]
What are we deciding is the current protocol version? 0.1?

**Comment by meatballs** [comment]
So, in total, I reckon we need to add:

- [ ] Name
- [ ] End Time
- [ ] Ritual ID
- [ ] Protocol Version

**Comment by theref** [comment]
- [ ] Submission storage location

**Comment by meatballs** [comment]
> Also, `ritual_id` of CBD DKG ceremony

Where do I get this?

**Comment by theref** [comment]
it's returned when the ritual is successfully initiated. The ritual is the large amount of work that writes a bunch of stuff on chain.
At the moment, there are only a couple of rituals (and therefore public keys) available. We hardcoded to use ritual_id `0`.
There are outstanding questions of whether to have an application wide public key, or a per vote public key. Part of the answer relies on the fee model of CBD.
Either way, the `ritual_id` for a vote needs to end up on chain.

**Comment by meatballs** [comment]
> We hardcoded to use ritual_id 0.

Where is that hard coded?

**Comment by theref** [comment]
> Where is that hard coded?
it was the fact that we had a public key in a secret env file. In reality, you want to store the `ritual_id` in the metadata, then read the public key from the threshold.network contract

> Also, storage location - is that the scroll rpc url or something else?
At the moment, the storage location is the same as the metadata location, but that **will** be too expensive for production. So the idea is to store the submissions somewhere cheaper (but still public). See https://github.com/electora-vote/electora-app/issues/19
