### ISSUE TITLE
Counting and Verification functionality

### ISSUE THREAD

**Issue by theref** [electora-vote/electora-app#25]
Simple application to demonstrate how to verify and count an election that has finished. Should possibly be a separate app to showcase that these processes are completely independent.

**Comment by meatballs** [comment]
I don't think it should be a separate app.

The whole premise of our app is that we provide convenience. Having to go somewhere else to see verification and counting is the very opposite of that.

No problem with us writing up how you might do that for yourself without using us, but we should put the whole lot in one place for the user.

**Comment by theref** [comment]
A lot of this work has been moved to https://github.com/electora-vote/electora-py and https://github.com/electora-vote/electora-bot
